### PR TITLE
Bumping versions

### PR DESCRIPTION
**Pull request by atooni**

### CODE REVIEW

**Comment by Ahnfelt** [comment]
Hi Andreas, thank you for the contribution! The pull request looks good, and I'm ready to accept it.

Formalia: Do you have the right to & agree to release the code contained in this pull request under the MIT License: https://opensource.org/licenses/MIT?

**Comment by atooni** [comment]
Hi, 

I am perfectly happy with the MIT License. Do you require an official document with a signature ?

**Comment by Ahnfelt** [comment]
No, I think this will do :)

**Comment by Ahnfelt** [comment]
Thank you for your contribution! I've merged the pull request and added you as a copyright holder to LICENSE.txt.

**Pull request merged**
