### PR TITLE
Add componentDidMount lifecycle method

### PR DESCRIPTION
**Pull request by erdeszt**

### CODE REVIEW

**Comment by Ahnfelt** [comment]
Thank you for your pull request. However, this is one of the life cycle methods that's intentionally missing in React4s.

The idea is that the constructor together with componentWillRender and componentWillUnmount is a complete set of lifecycle methods in React4s.

If you like, post some React4s example code where you would use componentDidMount, and we can discuss it.

**Comment by erdeszt** [comment]
I'm trying to integrate some jquery components into my react app and the recommended way is to do it in the `componentDidMount` method: https://reactjs.org/docs/integrating-with-other-libraries.html

I can post code but I think it unnecessary in this case. Let me know if you need more info or if you have a workaround for this use case 👍

**Comment by Ahnfelt** [comment]
Here's some pseudocode:

```scala
case class SomePlugin() extends Component[NoEmit] {
  var element = None

  def setElement(newElement) = {
    if(element != newElement) {
      element = $(newElement)
      element.somePlugin()
    }
  }

  def componentWillUnmount() = {
    element.somePlugin('destroy');
  }

  def render() = {
    E.div().withRef { e => setElement(Option(e)) }
  }
}
```

**Comment by erdeszt** [comment]
That seems to work in my case. I guess this PR can be closed.

One thing about `withRef` though, right now it expects a function from `Any` to `Unit`. Is there a way to narrow that `Any` down to something?

**Comment by Ahnfelt** [comment]
I think there are two options here. I could make it `js.Dynamic`, which is sometimes just enough to do what you want, or introduce http://scala-js.github.io/scala-js-dom/ as a dependency and make it `Element`. I've been hesitant to do the latter, since React4s currently has no dependencies.

Right now you can do `E.div().withRef { e => Option(e.asInstanceOf[js.Dymamic]).foreach(setElement) }`, which is pretty ugly but never fails.

**Comment by erdeszt** [comment]
I thought about this for a while and actually I'm not happy with either the workaround in general and the especially about the untyped `withRef`. 
Can you elaborate on **why** do you think it's a good idea to not expose `componentDidMount`?

**Comment by Ahnfelt** [comment]
It's not a *workaround*. Using `componentDidMount` for this is wrong in general. What happens if the `<div>` in question is not top-level, but inside an element whose presence is predicated on a prop?

**Comment by erdeszt** [comment]
> What happens if the <div> in question is not top-level, but inside an element whose presence is predicated on a prop?

`componentDidMount` has access to `Get` so I can just use the same prop I've used in the rendering of the `<div>`.
I'm still curious. What's the benefit of not having `componentDidMount`?

**Comment by Ahnfelt** [comment]
I think you're missing the point. `componentDidMount` doesn't run when the outer element disappears and comes back. So you'll end up using the `setElement` method anyway.

The benefit of having a less complicated lifecycle is that you'll have less bugs in your code due to using the lifecycle methods wrongly like this.

**Comment by erdeszt** [comment]
> I think you're missing the point. componentDidMount doesn't run when the outer element disappears and comes back.

I see your point, I didn't run into this issue myself so didn't consider it.

I've created a small example where your suggested solution seems to fail but `componentDidMount` works: https://gist.github.com/erdeszt/7f020045383658b755f89a86d5b85719
Here the `OnMountComponent` works as expected but the `WithRefComponent` recreates the jQuery component on every property change(because the element changes or the equality comparison on elements fail? I'm not sure).

I might be totally misusing react4s or misunderstanding your suggestion so feel free to correct me.

> The benefit of having a less complicated lifecycle is that you'll have less bugs in your code due to using the lifecycle methods wrongly like this.

I could twist this the other way around and say that by hiding official react lifecycle methods you force me to use alternative solutions which might lead to surprising behaviors like the one I linked.
I think there are valid use cases for both approaches and I'm asking you to reconsider merging this PR.

**Pull request closed without merging**
